### ISSUE TITLE
Command sent to my email doesn't work / json parsing error

### ISSUE THREAD

**Issue by Kehet** [Larawiz/issues#2]
### Explanation

Command sent to my email doesn't work

![image](https://user-images.githubusercontent.com/1544301/186993313-07d7b400-5b55-4215-a27b-4dfc36864424.png)

```
$ uname -a
Linux DESKTOP-RLN2QTP 5.10.102.1-microsoft-standard-WSL2 #1 SMP Wed Mar 2 00:30:59 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ php -v
PHP 8.0.21 (cli) (built: Jul 13 2022 08:26:22) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.21, Copyright (c) Zend Technologies
    with Zend OPcache v8.0.21, Copyright (c), by Zend Technologies

$ echo $SHELL
/usr/bin/zsh

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

### Blueprint

```yaml
# Welcome to Larawiz!
#
# This is an example Blog. Start by setting your models, and inside each the columns
# and migration methods. You can also create relations with the name and the type.
# If you want to go even further to save you hours, the docs link is at the top.

# You'll take less reading the docs than creating your app from scratch, since it is
# powered by the magic of brainded syntax™. Have a nice, excellent, productive day!

models:
  User:
    name: string
    email: string
    email_verified_at: timestamp nullable
    password: string
    is_admin: boolean default:false
    rememberToken: ~

    # You can declare relations as you would in a model: the name, the type, and
    # any other argument needed. Larawiz guesses the model from the column key.
    comments: hasMany
    posts: hasMany

  Post:
    id: uuid
    title: string
    body: longText
    published_at: timestamp nullable
    softDeletes: ~

    author: belongsTo:User
    comments: hasMany
    tags: belongsToMany # Larawiz takes care of the pivot table for you.

  Comment:
    body: string
    is_visible: boolean default:true
    author: belongsTo:User # There is no "Author" model, so we pinpoint it model.
    post: belongsTo

  Tag:
    name: string
    posts: belongsToMany # Yes, Larawiz will create the pivot table for you.
```

### Error

```php
$ composer create-project larawiz/larawiz my_blog --repository='{\"type\":\"package\",\"package\":{\"name\":\"larawiz/larawiz\",\"version\":\"1.0\",\"dist\":{\"url\":\"https://larawiz.com/storage/projects/M2BbklrLq1yUKBMpnX77xM0s6pqfvpCyUBh7cgpHAWM.zip\",\"type\":\"zip\"}}}' --stability=stable --remove-vcs
Creating a "larawiz/larawiz" project at "./my_blog"


  [Seld\JsonLint\ParsingException]
  "" does not contain valid JSON
  Parse error on line 1:
  {\"type\":\"package\"
  ^
  Expected one of: 'STRING', '}'


create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package>] [<directory>] [<version>]
```

### Are you a Sponsor?

No, don't give priority to this
