### ISSUE TITLE
blank page and generated result is wrong

### ISSUE THREAD

**Issue by mowses** [Larawiz/issues#3]
### Explanation

the page gets completely blank after I clear the contents of the editor on firefox
https://larawiz.com/

-----
the download content never changes after the first successfull generation, even if the next generations are completely different from the first.

### Blueprint

```yaml
# https://larawiz.com/


models:
  # database column types.
  DataType:
    name: string:64

  
  # json schema validation which you can apply to any input.
  ValidationRule:
    name: string:64
    description: text
    json: json

  
  # validation rule inputs.
  ValidationRuleInput:
    validationRule: belongsTo
    name: string:64
    dataType: belongsTo

    indexes:
      - columns: validation_rule name data_type
        type: unique


  # transform input to any output. Examples: convert string to uppercase, apply masks to variable values, or concat N vars together.
  Transformation:
    name: string:64
    description: text
    json: json


  # transformation inputs.
  TransformationInput:
    transformation: belongsTo
    name: string:64
    dataType: belongsTo

    indexes:
      - columns: transformation name data_type
        type: unique

  
  # transformation outputs.
  TransformationOutput:
    transformation: belongsTo
    name: string:64
    dataType: belongsTo

    indexes:
      - columns: transformation name data_type
        type: unique

  
  # any data value that can be stored, calculated or displayed. Database tables may be generated using these config. Example: a string(255) nullable field with "" as default value.
  Variable:
    name: string:64
    description: text
    dataType: belongsTo
    config: json

  
  # html templates.
  Template:
    file: string

  
  # a template may have placeholders for components, variables, templates, etc.
  TemplatePlaceholder:
    template: belongsTo
    placeholder: string:64
    allowedComponents: morphToMany:Component,allowed
    allowedTemplates: morphToMany:Template,allowed
    allowedVariables: morphToMany:Variable,allowed

    indexes:
      - columns: template placeholder
        type: unique

  
  # allowed types of data to template placeholders.
  TemplatePlaceholderAllowed:
    templatePlaceholder: belongsTo
    components: morphToMany:Component,allowed
    templates: morphToMany:Template,allowed
    variables: morphToMany:Variable,allowed


  # css themes to be applied to any template.
  Theme:
    file: string

  
  # a component is anything that has funcionality, template, theme, variable, etc.
  Component:
    name: string:64
    file: string  # javascript filepath

  
  # a component may have many variables which will be used as component input data for calculations, template displaying or anything else.
  ComponentVariable:
    component: belongsTo
    variable: belongsTo

  
  # a component may render different templates, but only one at time.
  ComponentTemplate:
    component: belongsTo
    template: belongsTo

  
  # a component template may have different themes, many at same time. Due to usage of class names at the most parent element.
  ComponentTemplateTheme:
    componentTemplate: belongsTo
    theme: belongsTo


migrations:
  template_placeholder_alloweds:
    allowed: morphs  # make sure that allowed_id is nullable
```

### Error

```php
---
```

### Are you a Sponsor?

No, don't give priority to this
