### ISSUE TITLE
Trying to create an app results in stuck modal

### ISSUE THREAD

**Issue by skills-up** [Larawiz/issues#7]
### Explanation

While trying to generate an app, the modal is getting stuck here:
<img width="671" alt="image" src="https://github.com/Larawiz/issues/assets/27212393/9c40a626-8501-44f7-b891-b50edd87c724">

### Blueprint

```yaml
models:
  User:
    name: string
    email: string
    email_verified_at: timestamp nullable
    password: string
    is_admin: boolean default:false
    rememberToken: ~

    # You can declare relations as you would in a model: the name, the type, and
    # any other argument needed. Larawiz guesses the model from the column key.
    comments: hasMany
    posts: hasMany

  Post:
    id: uuid
    title: string
    body: longText
    published_at: timestamp nullable
    softDeletes: ~

    author: belongsTo:User
    comments: hasMany
    tags: belongsToMany # Larawiz takes care of the pivot table for you.

  Comment:
    body: string
    is_visible: boolean default:true
    author: belongsTo:User # There is no "Author" model, so we pinpoint it model.
    post: belongsTo

  Tag:
    name: string
    posts: belongsToMany # Yes, Larawiz will create the pivot table for you.
```

### Error

```php
No error message is received
```

### Are you a Sponsor?

No, don't give priority to this
